# Generated by Django 3.2.7 on 2021-10-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewmodel',
            old_name='useful_revie_record',
            new_name='useful_review_record',
        ),
    ]
