#new_dirフォルダを作って、mounted_folderをmountする
#docker run -v <host>:<container>
#docker run -it -v C:/Users/nakam/Desktop/docker/mounted_folder:/new_dir 03eaffe35dc1 bash

FROM ubuntu:16.04
#mkdir無くても、マウントしたときに作成できるので、実は不要
RUN mkdir new_dir